<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="docker" nsURI="http://occiware.org/occi/docker/ecore" nsPrefix="docker">
  <eClassifiers xsi:type="ecore:EEnum" name="Mode">
    <eLiterals name="read_write" literal="read_write"/>
    <eLiterals name="read_only" value="1" literal="read_only"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Container Resource"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi.infrastructure/model/Infrastructure.ecore#//Compute"/>
    <eOperations name="create">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="start">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="stop">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="run">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="pause">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="unpause">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title" value=""/>
      </eAnnotations>
    </eOperations>
    <eOperations name="kill">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
      <eParameters name="signal" lowerBound="1">
        <eAnnotations source="OCCIE2Ecore">
          <details key="description"/>
        </eAnnotations>
        <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The name of this Container instance"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containerid">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The ID of this Container instance"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The image of this Container instance"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="build">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The build directory of this Container instance"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Override the default command in Dockerfile"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ports">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The ports of this Container instance"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expose">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The exposed ports of this Container instance"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volumes">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The list of volumes"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="environment">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Environment variables"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="env_file">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="net">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="'bridge',  'none', 'container:[name or id]', or 'host'"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dns">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Custom DNS servers"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dns_search">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Custom DNS search domains"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cap_add">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Add container capabilities"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cap_drop">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Drop container capabilities"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="working_dir">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Working directory"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entrypoint">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Entry point"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainname">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mem_limit">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory_swap">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Memory swap limit"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="privileged" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="restart">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stdin_open">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value=""/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interactive" lowerBound="1" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tty" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpu_shares" defaultValueLiteral="0">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="CPU shares for this Docker container"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pid">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="'' or 'host'"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ipc">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="'', 'host' or 'container:[name:id]'"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="add_host">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mac_address">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rm">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="security_opt">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="device">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lxc_conf">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpuset">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value=""/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publish_all" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Publish all exposed ports to random ports on the host interfaces"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="read_only" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Mount the container's root filesystem as read only"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitored" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="This attribut allow us to monitor the container"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpu_used">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="CPU consumed by the conatiner"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory_used">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Memory consumed by the container"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpu_percent" defaultValueLiteral="0">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The percentage of CPU used."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory_percent" defaultValueLiteral="0">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The percentage of Memory used."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disk_used">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The disk used."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disk_percent">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The percentage of disk used."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bandwidth_used">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The bandwidth used by the container."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bandwidth_percent">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The percentage of bandwith used."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitoring_interval" defaultValueLiteral="1000">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The time interval in which the metrics are retrieved from container. This value is in milliseconds."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpu_max_value">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The CPU max value espression used by the Gauge."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory_max_value">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The memory max value expression used by the gauge."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="core_max" defaultValueLiteral="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The maximum number core availbale on the machine. This value is setting dynamically."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedRef_20" upperBound="-1" eType="//Link"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Link between containers"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The alias of this Link instance"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkLink" eSuperTypes="//Link">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Volumesfrom">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="VolumsFrom"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="//Mode" defaultValueLiteral="read_write">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The mode of this VolumesFrom instance"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contains">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Link"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine Resource"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi.infrastructure/model/Infrastructure.ecore#//Compute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="engine_install_url">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Custom URL to use for engine installation [$MACHINE_DOCKER_INSTALL_URL]"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="engine_opt">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Specify arbitrary flags to include with the created engine in the form flag=value"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="engine_insecure_registry">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Specify insecure registries to allow with the created engine"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="engine_registry_mirror">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Specify registry mirrors to use [$ENGINE_REGISTRY_MIRROR]"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="engine_label">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Specify labels for the created engine"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="engine_storage_driver">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Specify a storage driver to use with the engine"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="engine_env">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Specify environment variables to set in the engine"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swarm">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Configure Machine with Swarm"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swarm_image">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Specify Docker image to use for Swarm [$MACHINE_SWARM_IMAGE]"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swarm_master">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Configure Machine to be a Swarm master"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swarm_discovery">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Discovery service to use with Swarm"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swarm_strategy">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Define a default scheduling strategy for Swarm"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swarm_opt">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Define arbitrary flags for swarm"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swarm_host">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="ip/socket to listen on for Swarm master"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swarm_addr">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="addr to advertise for Swarm (default: detect and use the machine IP)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swarm_experimental">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Enable Swarm experimental features"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tls_san">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Support extra SANs for TLS certs"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Volume">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Volume disk"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi.infrastructure/model/Infrastructure.ecore#//Storage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driver" defaultValueLiteral="local">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value=" Specify volume driver name (default &quot;local&quot;)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Set metadata for a volume (default [])"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="options">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Set driver specific options (default map[])"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The volume Mountpoint ex. the /host/directory"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destination">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The volume name inside the container ex. /container/path"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Specify volume driver name"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rw">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The volume Read/Write access"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propagation">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The volume propagation"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The volume name."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Network resource"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi.infrastructure/model/Infrastructure.ecore#//Network"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="networkId">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The network ID retreived when the creation is done"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The network name"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aux_address">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Auxiliary IPv4 or IPv6 addresses used by Network driver (default map[])"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driver">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Driver to manage the Network (default &quot;bridge&quot;)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gateway">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="IPv4 or IPv6 Gateway for the master subnet (default [])"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="internal">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Restrict external access to the network"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip_range">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Allocate container ip from a sub-range (default [])"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ipam_driver">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="IP Address Management Driver (default &quot;default&quot;)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ipam_opt">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Set IPAM driver specific options (default map[])"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ipv6">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Enable IPv6 networking"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opt">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Set driver specific options (default map[])"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subnet">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Subnet in CIDR format that represents a network segment (default [])"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_Generic" eSuperTypes="//Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Create machines using an existing VM/Host with SSH"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="engine_port" defaultValueLiteral="2376">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Port to use for Docker Daemon (Note: This flag will not work with boot2docker)."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip_address" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value=" required IP Address of host."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssh_key">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Path to the SSH user private key."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssh_user" defaultValueLiteral="root">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="SSH username used to connect."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssh_port" defaultValueLiteral="22">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Port to use for SSH."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_Amazon_EC2" eSuperTypes="//Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine on Amazon EC2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access_key" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Your access key id for the Amazon Web Services API"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ami" defaultValueLiteral="ami-4ae27e22">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The AMI ID of the instance to use"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instance_type" defaultValueLiteral="t2.micro">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The instance type to run"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="region" defaultValueLiteral="us-east-1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The region to use when launching the instance"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="root_size" defaultValueLiteral="16">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The root disk size of the instance (in GB)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secret_key" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Your secret access key for the Amazon Web Services API"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="security_group" defaultValueLiteral="docker-machine">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="AWS VPC security group name"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="session_token">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Your session token for the Amazon Web Services API"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subnet_id">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="AWS VPC subnet id"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vpc_id" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Your VPC ID to launch the instance in"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zone" defaultValueLiteral="a">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The AWS zone launch the instance in (i.e. one of a,b,c,d,e)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_Digital_Ocean" eSuperTypes="//Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine on Digital Ocean"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access_token" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Your personal access token for the Digital Ocean API"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" defaultValueLiteral="docker">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The name of the Digital Ocean image to use"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="region" defaultValueLiteral="nyc3">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The region to create the droplet in"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" defaultValueLiteral="512mb">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The size of the Digital Ocean driver (larger than default options are of the form 2gb)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_Google_Compute_Engine" eSuperTypes="//Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine on Google Compute Engine"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zone" defaultValueLiteral="us-central1-a">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The zone to launch the instance"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machine_type" defaultValueLiteral="f1-micro">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The type of instance"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" defaultValueLiteral="docker-user">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The username to use for the instance"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instance_name" defaultValueLiteral="docker-machine">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The name of the instance"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="project" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The name of your project to use when launching the instance"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_IBM_SoftLayer" eSuperTypes="//Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine on IBM SoftLayer"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="api_endpoint" defaultValueLiteral="api.softlayer.com/rest/v3">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Change softlayer API endpoint"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="username for your softlayer account, api key needs to match this user"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="api_key" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="API key for your user account"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpu">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Number of CPU's for the machine"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disk_size">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Size of the disk in MB. 0 sets the softlayer default"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="domain name for the machine"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hourly_billing" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Sets the hourly billing flag (default), otherwise uses monthly billing"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" defaultValueLiteral="UBUNTU_LATEST">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="OS Image to use"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="local_disk" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Use local machine disk instead of softlayer SAN"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="private_net_only">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Disable public networking"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="region">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="softlayer region"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="public_vlan_id" defaultValueLiteral="0">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Your public VLAN ID."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="private_vlan_id" defaultValueLiteral="0">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Your private VLAN ID."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_Microsoft_Azure" eSuperTypes="//Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine on Microsoft Azure"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subscription_id" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Your Azure subscription ID (A GUID like d255d8d7-5af0-4f5c-8a3e-1545044b861e)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subscription_cert" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Your Azure subscription cert"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="environment" defaultValueLiteral="AzurePublicCloud">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Azure environment (e.g. AzurePublicCloud, AzureChinaCloud)."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Azure region to create the virtual machine."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resource_group" defaultValueLiteral="docker-machine">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Azure Resource Group name to create the resources in."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Size for Azure Virtual Machine."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssh_user">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Username for SSH login."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vnet" defaultValueLiteral="docker-machine">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Azure Virtual Network name to connect the virtual machine. To specify a Virtual Network from another resource group, use resourcegroup:vnet-name format."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subnet">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Azure Subnet Name to be used within the Virtual Network."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subnet_prefix" defaultValueLiteral="192.168.0.0/16">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Private CIDR block. Used to create subnet if it does not exist. Must match in the case that the subnet does exist."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availability_set" defaultValueLiteral="docker-machine">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Azure Availability Set to place the virtual machine into."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="open_port">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value=" Make additional port number(s) accessible from the Internet"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="private_ip_address">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Specify a static private IP address for the machine."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="no_public_ip">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Do not create a public IP address for the machine (implies --azure-use-private-ip). "/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static_public_ip">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Assign a static public IP address to the machine."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="docker_port" defaultValueLiteral="2376">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Port number for Docker engine."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="use_private_ip">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value=" Use private IP address of the machine to connect. It&#x2019;s useful for managing Docker machines from another machine on the same network e.g. while deploying Swarm."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Azure virtual machine image in the format of Publisher:Offer:Sku:Version"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_Microsoft_Hyper_V" eSuperTypes="//Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine on Microsoft Hyper-V"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtual_switch">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Name of the virtual switch to use."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boot2docker_url">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The URL of the boot2docker iso. Defaults to the latest available version"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disk_size" defaultValueLiteral="20000">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Size of disk for the host in MB"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static_macaddress">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Hyper-V network adapter&#x2019;s static MAC address."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vlan_id">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Hyper-V network adapter&#x2019;s VLAN ID if any."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_OpenStack" eSuperTypes="//Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine on OpenStack"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flavor_id" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The flavor ID to use when creating the machine"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flavor_name">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The OS FLAVOR NAME"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image_id" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The image ID to use when creating the machine"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image_name">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The OS IMAGE NAME"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auth_url" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Keystone service base URL"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="User identifer to authenticate with"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="User password. It can be omitted if the standard environment variable OS_PASSWORD is set."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tenant_name">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Identify the tenant in which the machine will be created"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tenant_id">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Identify the tenant in which the machine will be created"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="region">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The region to work on. Can be omitted if there is only one region on the OpenStack"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endpoint_type" defaultValueLiteral="publicURL">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Endpoint type can be internalURL, adminURL on publicURL. If is a helper for the driver to choose the right URL in the OpenStack service catalog. If not provided the default id publicURL"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="net_id">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The private network id the machine will be connected on. If your OpenStack project project contains only one private network it will be use automatically"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="net_name">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The OS NETWORK NAME"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sec_groups">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="If security groups are available on your OpenStack you can specify a comma separated list to use for the machine (e.g. secgrp001,secgrp002)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="floatingip_pool">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The IP pool that will be used to get a public IP an assign it to the machine. If there is an IP address already allocated but not assigned to any machine, this IP will be chosen and assigned to the machine. If there is no IP address already allocated a new IP will be allocated and assigned to the machine"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active_timeout" defaultValueLiteral="200">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The OS ACTIVE TIMEOUT"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availability_zone">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The OS AVAILABILITY ZONE"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain_id">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The OS DOMAIN ID"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain_name">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The OS DOMAIN NAME"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insecure" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The OS INSECURE"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip_version" defaultValueLiteral="4">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The OS IP VERSION"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keypair_name">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The OS KEYPAIR NAME"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="private_key_file">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The OS PRIVATE KEY FILE"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssh_port" defaultValueLiteral="22">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The OS SSH PORT"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssh_user" defaultValueLiteral="root">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The OS SSH USER"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_Rackspace" eSuperTypes="//Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine on Rackspace cloud"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Rackspace account username"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="api_key" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Rackspace API key"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="region" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Rackspace region name"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endpoint_type" defaultValueLiteral="publicURL">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Rackspace endpoint type (adminURL, internalURL or the default publicURL)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image_id" defaultValueLiteral="59a3fadd-93e7-4674-886a-64883e17115f">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Rackspace image ID "/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flavor_id" defaultValueLiteral="general1-1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Rackspace flavor ID"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssh_user" defaultValueLiteral="root">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="SSH user for the newly booted machine"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssh_port" defaultValueLiteral="22">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="SSH port for the newly booted machine"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="docker_install" defaultValueLiteral="true">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Set if Docker has to be installed on the machine."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_VirtualBox" eSuperTypes="//Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine on VirtualBox"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boot2docker_url">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The URL of the boot2docker image. Default to the latest available version"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disk_size" defaultValueLiteral="20000">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Size of disk for the host in MB"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host_dns_resolver" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The VIRTUALBOX HOST DNS RESOLVER&#x9;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="import_boot2docker_vm">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The VIRTUALBOX BOOT2DOCKER IMPORT VM"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostonly_cidr" defaultValueLiteral="192.168.99.1/24">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The VIRTUALBOX HOSTONLY CIDR"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostonly_nictype" defaultValueLiteral="82540EM">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The &#x9;VIRTUALBOX HOSTONLY NIC TYPE"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostonly_nicpromisc" defaultValueLiteral="deny">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The VIRTUALBOX HOSTONLY NIC PROMISC"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="no_share" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The VIRTUALBOX NO SHARE"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="no_dns_proxy" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The VIRTUALBOX NO DNS PROXY"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="no_vtx_check" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The VIRTUALBOX NO VTX CHECK"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="share_folder">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The VIRTUALBOX SHARE FOLDER"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_VMware_Fusion" eSuperTypes="//Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine on VMware Fusion"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boot2docker_url">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="URL for boot2docker image"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disk_size" defaultValueLiteral="20000">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Size of disk for host VM (in MB)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory_size" defaultValueLiteral="1024">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Size of memory for host VM (in MB)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="no_share" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Disable the mount of your home directory."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_VMware_vCloud_Air" eSuperTypes="//Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine on VMware vCloud Air"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="vCloud Air Username"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="vCloud Air Password"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="catalog" defaultValueLiteral="Public Catalog">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Catalog "/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="catalogitem" defaultValueLiteral="Ubuntu Server 12.04 LTS (amd64 20140927)">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Catalog Item "/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="computeid">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Compute ID (if using Dedicated Cloud)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpu_count" defaultValueLiteral="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="VM Cpu Count"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="docker_port" defaultValueLiteral="2376">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Docker port "/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edgegateway" defaultValueLiteral="&lt;vdcid>">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Organization Edge Gateway"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory_size" defaultValueLiteral="2048">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="VM Memory Size in MB"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vapp_name" defaultValueLiteral="&lt;autogenerated>">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="vApp Name"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orgvdcnetwork" defaultValueLiteral="&lt;vdcid>-default-routed">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Organization VDC Network to attach"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provision" defaultValueLiteral="true">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Install Docker binaries"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicip">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Org Public IP to use"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssh_port" defaultValueLiteral="22">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="SSH port"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vdcid">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Virtual Data Center ID"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_VMware_vSphere" eSuperTypes="//Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine on VMware vSphere"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="vSphere Username"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="vSphere Password"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boot2docker_url" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="URL for boot2docker image"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compute_ip">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Compute host IP where the Docker VM will be instantiated"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpu_count" defaultValueLiteral="2">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="CPU number for Docker VM"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datacenter">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Datacenter for Docker VM (must be set to ha-datacenter when connecting to a single host)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datastore">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Datastore for Docker VM"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disk_size" defaultValueLiteral="20000">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Size of disk for Docker VM (in MB)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory_size" defaultValueLiteral="2048">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Size of memory for Docker VM (in MB) "/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="network">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Network where the Docker VM will be attached"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pool">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Resource pool for Docker VM"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vcenter">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value=" IP/hostname for vCenter (or ESXi if connecting directly to a single host)"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
