<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hr" nsURI="http://www.example.eclipse.org/Library3" nsPrefix="library3">
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Person"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="name"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" lowerBound="1">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="library"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="../../../collector/dataset_repos/pairs/tests_org.eclipse.emf.test.tools_data_ant.expected_models_5.0_reload_library.xsds_emf_hr__0ed4d92__06e9590/library.ecore#//Library"/>
      <eOpposite href="../../../collector/dataset_repos/pairs/tests_org.eclipse.emf.test.tools_data_ant.expected_models_5.0_reload_library.xsds_emf_hr__0ed4d92__06e9590/library.ecore#//Library/employees"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
