<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="security" nsURI="http://security/1.0" nsPrefix="security">
  <eClassifiers xsi:type="ecore:EClass" name="Principal" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserAccount">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceAccount">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="token">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
