<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hypervisor" nsURI="http://occiware.org/hypervisor" nsPrefix="hypervisor">
  <eClassifiers xsi:type="ecore:EEnum" name="CLOCK">
    <eLiterals name="offset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FEATURES">
    <eLiterals name="acpi"/>
    <eLiterals name="pae"/>
    <eLiterals name="apic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OS">
    <eLiterals name="type"/>
    <eLiterals name="boot"/>
    <eLiterals name="kernel"/>
    <eLiterals name="ramdisk"/>
    <eLiterals name="cmdline"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine resource"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi.infrastructure/model/Infrastructure.ecore#//Compute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Hypervisor name."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boot">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The machine boot device."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The machine unique ID."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" defaultValueLiteral="localtime">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="This will be set if the guest XML contains a request for a clock synced to localtime."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="os_type" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contains">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Link"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Disk">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Disk resource"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi.infrastructure/model/Infrastructure.ecore#//Storage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" defaultValueLiteral="Disk">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The default name of the resource"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The kind of disk."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="device" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Specify the disk device's."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" defaultValueLiteral="false">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target_dev">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target_bus">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Interface resource"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi.infrastructure/model/Infrastructure.ecore#//Network"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" defaultValueLiteral="interface">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The interface resource"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The interface type"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The interface model"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mac_addresss">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="route">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_VirtualBox" eSuperTypes="//Machine">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Machine on VirtualBox"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" defaultValueLiteral="hvm">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="This type is specific to Libvirt."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="features" eType="//FEATURES" defaultValueLiteral="acpi">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The flag specify the Advanced Configuration and Power Interface(ACPI), the Physical Address Extension (PAE) and the Advanced Programmable Interrupt Controller (APIC)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="on_poweroff">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Action to do when the machine is poweroff."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="on_reboot">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Action to do when the machine is rebooting."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="on_crash">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Action to do when the machine crached."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum_memory" lowerBound="1" defaultValueLiteral="256000">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="This sets the maximum memory for the guest at boot time in KB."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="current_memory">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="This sets the lower memory for the guest at boot time in KB."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vcpu" defaultValueLiteral="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The number of virtual CPUs to create."/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bridge" eSuperTypes="//Interface">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Bridge interface"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source_bridge">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="//Interface">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="User interface"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parallel">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Parallel resource"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" defaultValueLiteral="parallel">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="The parallel resource name"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Serial">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Serial resource"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" defaultValueLiteral="serial">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Direct" eSuperTypes="//Interface">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Direct Interface"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source_dev">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source_mode">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ethernet">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="Ethernet resource"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target_dev">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="script_path">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
