<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="linkeddata" nsURI="http://occiware.org/linkeddata/ecore" nsPrefix="linkeddata">
  <eClassifiers xsi:type="ecore:EEnum" name="Lifecycle">
    <eLiterals name="draft"/>
    <eLiterals name="published" value="1" literal="published"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Robustness">
    <eLiterals name="cluster" literal="cluster"/>
    <eLiterals name="node" value="1"/>
    <eLiterals name="none" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ldproject">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="LDProject"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Resource"/>
    <eOperations name="publish">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="unpublish">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="update">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lifecycle" eType="//Lifecycle">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="robustness" eType="//Robustness">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lddatabaselink">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title" value="LDDatabaseLink"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="database" lowerBound="1" defaultValueLiteral="datacore">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" defaultValueLiteral="27017">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ldprojectlink">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title"/>
    </eAnnotations>
    <eSuperTypes href="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Link"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewConcept_35">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
