<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="change" nsURI="http://www.eclipse.org/emf/2003/Change" nsPrefix="change">
  <eClassifiers xsi:type="ecore:EClass" name="ChangeDescription" abstract="true">
    <eOperations name="apply"/>
    <eOperations name="applyAndReverse"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectChanges" upperBound="-1" eType="//EObjectToChangesMapEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectsToDetach" upperBound="-1" transient="true" derived="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectsToAttach" upperBound="-1" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceChanges" upperBound="-1" eType="//ResourceChange" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectToChangesMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1" eType="//FeatureChange" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureChange">
    <eOperations name="apply">
      <eParameters name="originalObject">
        <eType xsi:type="ecore:EClass" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="applyAndReverse">
      <eParameters name="originalObject">
        <eType xsi:type="ecore:EClass" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" volatile="true" unsettable="true">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataValue" volatile="true">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="set" defaultValueLiteral="true">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" changeable="false" volatile="true" transient="true" derived="true">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1" volatile="true" unsettable="true">
      <eType xsi:type="ecore:EClass" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceValue" volatile="true">
      <eType xsi:type="ecore:EClass" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listChanges" upperBound="-1" eType="//ListChange" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListChange">
    <eOperations name="apply">
      <eParameters name="originalList">
        <eGenericType>
          <eTypeArguments>
            <eClassifier xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
          </eTypeArguments>
          <eClassifier xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EEList"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="applyAndReverse">
      <eParameters name="originalList">
        <eGenericType>
          <eTypeArguments>
            <eClassifier xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
          </eTypeArguments>
          <eClassifier xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EEList"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="//ChangeKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataValues" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" defaultValueLiteral="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moveToIndex">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" upperBound="-1" volatile="true" transient="true" derived="true">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceValues" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature">
      <eType xsi:type="ecore:EClass" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureMapEntryValues" upperBound="-1" eType="//FeatureMapEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChangeKind">
    <eLiterals name="ADD"/>
    <eLiterals name="REMOVE" value="1"/>
    <eLiterals name="MOVE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceChange">
    <eOperations name="apply"/>
    <eOperations name="applyAndReverse"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceURI">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resource" transient="true" derived="true">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EResource"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType>
        <eTypeArguments/>
        <eClassifier xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EEList"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listChanges" upperBound="-1" eType="//ListChange" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureMapEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" volatile="true" unsettable="true">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataValue" volatile="true">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" changeable="false" volatile="true" transient="true" derived="true">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1" volatile="true" unsettable="true">
      <eType xsi:type="ecore:EClass" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceValue" volatile="true">
      <eType xsi:type="ecore:EClass" href="../../../collector/dataset_repos/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
