<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hypervisor" nsURI="http://occiware.org/hypervisor" nsPrefix="hypervisor">
  <eClassifiers xsi:type="ecore:EEnum" name="CLOCK">
    <eLiterals name="offset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FEATURES">
    <eLiterals name="acpi"/>
    <eLiterals name="pae"/>
    <eLiterals name="apic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OS">
    <eLiterals name="type"/>
    <eLiterals name="boot"/>
    <eLiterals name="kernel"/>
    <eLiterals name="ramdisk"/>
    <eLiterals name="cmdline"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine">
    <eSuperTypes href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi.infrastructure/model/Infrastructure.ecore#//Compute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boot">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" defaultValueLiteral="localtime">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="os_type" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augmentedValue_25">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contains">
    <eSuperTypes href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Link"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Disk">
    <eSuperTypes href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi.infrastructure/model/Infrastructure.ecore#//Storage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" defaultValueLiteral="Disk">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="device" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" defaultValueLiteral="false">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Boolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target_dev">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target_bus">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eSuperTypes href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi.infrastructure/model/Infrastructure.ecore#//Network"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" defaultValueLiteral="interface">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mac_addresss">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="route">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine_VirtualBox" eSuperTypes="//Machine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" defaultValueLiteral="hvm">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="features" eType="//FEATURES" defaultValueLiteral="acpi"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="on_poweroff">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="on_reboot">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="on_crash">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="current_memory">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vcpu" defaultValueLiteral="1">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Number"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bridge" eSuperTypes="//Interface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source_bridge">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="//Interface"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parallel">
    <eSuperTypes href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" defaultValueLiteral="parallel">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Serial">
    <eSuperTypes href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" defaultValueLiteral="serial">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Direct" eSuperTypes="//Interface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source_dev">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source_mode">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ethernet">
    <eSuperTypes href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target_dev">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="script_path">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filesystem">
    <eSuperTypes href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" defaultValueLiteral="filesystem">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="../../../collector/dataset_repos/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
